version = "3.10.7"
runner.dialect = scala3
maxColumn = 120
indent.main = 4
newlines.topLevelStatementBlankLines = [
  { maxNest = 0, blanks = 3 } // uses 2 blanks for all unindented statements
  { regex = "^Import" } // excludes import groups; blanks are not specified
]
